import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html style={{ minHeight: "100vh" }} lang="en">
      <body style={{ height: "100%", backgroundImage: "url(/bg.png)", backgroundRepeat: "no-repeat", backgroundSize: "cover" }} className={`px-4 py-4`}>
        <Header />
        <main className='p-4 border-1 border-primary rounded-lg bg-beige-1'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
